### ISSUE TITLE
Yurok Inn Upper Floor disappearing

### ISSUE THREAD

**Issue by matthewschroeder12** [omarwright07/age-of-occam#162]
Upper floor just... disappeared? Lower floor still appears though. Not sure how it happened. Order of events was: Added static mesh -> labelled it "Test Floor 1" -> did that 3 times using the interior floor pieces to see if I could replace the current dock tiles -> saved -> it was fine -> removed them -> magically gone -> won't come back no matter what

![image](https://user-images.githubusercontent.com/102920321/197328446-93995c0f-ad83-4c16-a620-d696d63e85ad.png)

**Comment by omarwright07** [comment]
The interior pieces weren't child to the interior component
