### ISSUE TITLE
Walking Direction Bug

### ISSUE THREAD

**Issue by matthewschroeder12** [omarwright07/age-of-occam#2]
Specifically on the Swamplands map, when the protagonist walks left or right they will go in the opposite direction. Walking up and down works fine.

**Comment by omarwright07** [comment]
The world actor blueprint is flipped when spawned in the Swamplands map

**Comment by omarwright07** [comment]
It was the rotation of the "player start" actor that caused the actor to face the opposite direction. This can't be overridden and not having one will have the rotation be random, so everyone needs to avoid rotating the player start once place. 

#Note: the default rotation of placing the player start is already start to true world north.
